# Generated by Django 4.0.2 on 2022-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('oldprice', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='Home\\mensimg\\images')),
            ],
        ),
    ]
