# Generated by Django 4.0.2 on 2022-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Sale_or_not', models.CharField(default='No Sale', max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='Home\\ccessories\\images')),
                ('descriptions', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Sale_or_not', models.CharField(default='No Sale', max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='Home\\kidsimg\\images')),
                ('descriptions', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Sale_or_not', models.CharField(default='No Sale', max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='Home\\womensimg\\images')),
                ('descriptions', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mens',
            name='oldprice',
        ),
        migrations.AddField(
            model_name='mens',
            name='Sale_or_not',
            field=models.CharField(default='No Sale', max_length=50),
        ),
        migrations.AddField(
            model_name='mens',
            name='descriptions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mens',
            name='price',
            field=models.FloatField(),
        ),
    ]
