# Generated by Django 4.0.2 on 2022-04-08 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_order_delete_accessories_delete_kids_delete_womens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsqr',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('TransactionID', models.IntegerField()),
                ('UPINumber', models.IntegerField()),
                ('UPIIDHAi', models.CharField(default='none', max_length=50)),
                ('Filehai', models.ImageField(default='', upload_to='Home\\qrdetails\\images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
