# Generated by Django 4.0.2 on 2022-04-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_detailsqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CODHai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='UPIHai',
            field=models.BooleanField(default=False),
        ),
    ]
