# Generated by Django 4.0.2 on 2022-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='ok', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
