# Generated by Django 4.0.4 on 2022-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mens',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
