# Generated by Django 4.0.2 on 2022-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_mens_category_alter_mens_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productorder',
            field=models.BooleanField(default=False),
        ),
    ]
