# Generated by Django 4.0.2 on 2022-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_order_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jsonCart',
            field=models.CharField(max_length=1500),
        ),
    ]
